### ISSUE TITLE
Custom decimal separators not working with pipelines

### ISSUE THREAD

**Issue by nightsh** [openspending/openspending#1457]
I have a test dataset, 5 rows in total, all of them with custom group/decimal separators. Values look like a joined string in the database.

In my example, these values:

```
84.719.000,00 | 78.644.000,00 | 77.946.067,23
716.000,00 | 1.155.200,00 | 1.034.332,96
14.599.512,00 | 13.544.512,00 | 13.345.102,23
9.185.000,00 | 9.185.000,00 | 7.463.398,08
3.385.000,00 | 3.880.000,00 | 3.312.059,19
```

end up in postgres like this (sorry for uneven formatting, different clipboard sources):

```
"8471900000"	"7864400000"	"7794606723"
"71600000"	"115520000"	"103433296"
"1459951200"	"1354451200"	"1334510223"
"918500000"	"918500000"	"746339808"
"338500000"	"388000000"	"331205919"
```

An example of measure spec for one of the columns (they're all the same, except names):

```
- header: proposed_value
  title: "Izvorni plan"
  options:
    currency: HRK
    phase: proposed
    decimalChar: ","
    groupChar: "."
  columnType: value
```

Here is the dataset (needs a `gunzip`): [test.csv.gz](https://github.com/openspending/openspending/files/3258316/test.csv.gz)

Here is the spec: [fiscal.source-spec.yaml.gz](https://github.com/openspending/openspending/files/3258341/fiscal.source-spec.yaml.gz)

Both are based on the [real data from Croatia](https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:croatia-budget-spending).

_Originally posted by @nightsh in https://github.com/openspending/os-source-specs/pull/28#issuecomment-499174981_
